[package]
publish = false
name = "queue-remote"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
doctest = false

[dependencies]
async-trait = { workspace = true }
aws-sigv4-signing = { workspace = true }
http = { workspace = true }
http-request = { workspace = true }
queue-provider = { path = "../queue-provider" }
serde = { workspace = true }
serde_json = { workspace = true }
storage-types = { path = "../storage-types" }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
httpmock = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
