[package]
edition = "2024"
license.workspace = true
name = "storage-provider"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
async-trait = { workspace = true }
bg-jobs = { path = "../bg-jobs" }
metrics-facade = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
storage-backfill = { path = "../storage-backfill" }
storage-condition = { path = "../storage-condition" }
storage-sync = { path = "../storage-sync" }
storage-types = { path = "../storage-types" }
tokio = { workspace = true }

[dev-dependencies]
alloc-counter = { workspace = true }
anyhow = { workspace = true }
quint-connect = { workspace = true }

[lints]
workspace = true
