[package]
publish = false
edition = "2024"
license.workspace = true
name = "pubsub"
version = "0.1.0"

[lib]
doctest = false

[[bin]]
name = "pubsub"
path = "src/main/mod.rs"

[features]
default = ["sqlite", "server"]
server = ["dep:axum", "dep:clap", "dep:tracing-subscriber", "dep:uuid"]
sqlite = ["dep:sql", "sql/sqlite-backend", "queue/sqlite", "stream/sqlite"]
turso = [
    "dep:sql",
    "sql/sqlite-backend",
    "sql/turso-backend",
    "queue/turso",
    "stream/turso",
]
postgres = ["dep:sql", "sql/postgres-backend", "queue/postgres", "stream/postgres"]
rocksdb = ["dep:kv", "kv/rocksdb-backend", "queue/rocksdb", "stream/rocksdb"]
foundationdb = [
    "dep:kv",
    "kv/foundationdb-backend",
    "queue/foundationdb",
    "stream/foundationdb",
]

[dependencies]
axum = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
config = { path = "../config" }
http-error = { path = "../http-error" }
http-request = { workspace = true }
kv = { path = "../kv", optional = true }
pubsub-provider = { path = "../pubsub-provider" }
queue = { path = "../queue" }
queue-provider = { path = "../queue-provider" }
serde = { workspace = true }
serde_json = { workspace = true }
sql = { path = "../sql", optional = true, default-features = false }
storage-types = { path = "../storage-types" }
stream = { path = "../stream", default-features = false }
stream-provider = { path = "../stream-provider" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
url = { workspace = true }
uuid = { workspace = true, optional = true }

[dev-dependencies]
aws-config = { workspace = true }
aws-sdk-sns = { workspace = true }

[lints]
workspace = true
