[package]
edition = "2024"
license.workspace = true
name = "pubsub-provider"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
async-trait = { workspace = true }
http-error = { path = "../http-error" }
serde = { workspace = true }
serde_json = { workspace = true }
storage-types = { path = "../storage-types" }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
