[package]
publish = false
edition = "2024"
license.workspace = true
name = "stream"
version = "0.1.0"

[lib]
doctest = false

[features]
default = ["sqlite"]
sqlite = ["dep:sql", "sql/sqlite-backend"]
turso = ["dep:sql", "sql/sqlite-backend", "sql/turso-backend"]
postgres = ["dep:sql", "sql/postgres-backend"]
rocksdb = ["dep:kv"]
foundationdb = ["dep:kv", "kv/foundationdb-backend"]

[dependencies]
kv = { path = "../kv", optional = true }
sql = { path = "../sql", optional = true, default-features = false }
storage-provider = { path = "../storage-provider" }
storage-types = { path = "../storage-types" }
stream-provider = { path = "../stream-provider" }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
