pub const DEFAULT_CONFIG_VERSION: &str = "1.0";
pub const DEFAULT_HTTP_BIND_ADDR: &str = "0.0.0.0:8080";
pub const DEFAULT_SLOW_OPERATION_LOG_THRESHOLD_MS: u64 = 500;

pub const DEFAULT_STORAGE_SQLITE_DB_PATH: &str = "/var/lib/aux-storage/db/sqlite/main.db";
pub const DEFAULT_STORAGE_TURSO_DB_PATH: &str = "main.turso.db";
pub const DEFAULT_STORAGE_ROCKS_DB_PATH: &str = "/var/lib/aux-storage/db/rocksdb";
pub const DEFAULT_REMOTE_REGION: &str = "us-east-1";

pub const DEFAULT_TRACING_LOG_LEVEL: &str = "warn";
pub const DEFAULT_LOG_DESTINATION: &str = "stdout";

pub const DEFAULT_STORAGE_POINT_READ_CACHE_CAPACITY: usize = 1_000_000;
pub const DEFAULT_STORAGE_POINT_READ_CACHE_MEGABYTES_PER_CORE: u64 = 100;
pub const DEFAULT_STORAGE_POINT_READ_CACHE_TTL_SECONDS: u64 = 300;
pub const DEFAULT_STORAGE_QUERY_PROOF_CACHE_MAX_QUERY_SPACES: usize = 2_048;
pub const DEFAULT_STORAGE_QUERY_PROOF_CACHE_MAX_MANIFEST_ENTRIES: usize = 200_000;
pub const DEFAULT_STORAGE_QUERY_PROOF_CACHE_MAX_COVERAGE_RANGES: usize = 20_000;
pub const DEFAULT_DISTRIBUTED_CACHE_VNODES_PER_NODE: usize = 64;

pub const DEFAULT_JOBS_MAX_IMMEDIATE_WORKERS: usize = 8;
pub const DEFAULT_JOBS_JITTER_PERCENT: u8 = 10;
pub const DEFAULT_STORAGE_REPLICATION_POLL_INTERVAL_MS: u64 = 1_000;
pub const DEFAULT_STORAGE_REPLICATION_HEARTBEAT_INTERVAL_MS: u64 = 5_000;
pub const DEFAULT_STORAGE_REPLICATION_HEARTBEAT_JITTER_MS: u64 = 500;
pub const DEFAULT_STORAGE_REPLICATION_BATCH_MUTATION_LIMIT: u32 = 100;
pub const DEFAULT_STORAGE_REPLICATION_BATCH_BYTE_LIMIT: u64 = 4 * 1024 * 1024;
pub const DEFAULT_STORAGE_SYNC_REPLICATION_ELECTION_TIMEOUT_MS: u64 = 300;
pub const DEFAULT_STORAGE_SYNC_REPLICATION_HEARTBEAT_INTERVAL_MS: u64 = 50;
pub const DEFAULT_STORAGE_SYNC_REPLICATION_PROPOSAL_COALESCING_WINDOW_US: u64 = 500;

pub const DEFAULT_QUEUE_VISIBILITY_TIMEOUT_SECONDS: u32 = 30;
pub const DEFAULT_QUEUE_MESSAGE_RETENTION_SECONDS: u32 = 345_600;
