[package]
edition = "2024"
license.workspace = true
name = "queue-provider"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
http-error = { path = "../http-error" }
md5 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
storage-types = { path = "../storage-types" }
thiserror = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
alloc-counter = { workspace = true }

[lints]
workspace = true
